Vagrant.configure("2") do |config|
  config.vm.provision :file, source: '~/.bashrc',
                             destination: '/home/vagrant/.bashrc'
  config.vm.provision :file, source: '~/.inputrc',
                             destination: '/home/vagrant/.inputrc'
end
